### ISSUE TITLE
[Feature Request] How can i see architecture of this project

### ISSUE THREAD

**Issue by HelloTo4x** [Grasscutters/Grasscutter#1091]
Hi all, how can see the architecture of this project

**Comment by zhaodice** [comment]
this project has not native assembly code

**Comment by HelloTo4x** [comment]
i mean i want to see architecture before contributing

**Comment by 4Benj** [comment]
What?

**Comment by kyoko12** [comment]
You mean the project structure? Just read the code?

**Comment by HelloTo4x** [comment]
> What?

i really need to know the architecture of this code, can u share me some your knowledge about it

**Comment by Birdulon** [comment]
There's no design outlines beyond the code.

**Comment by lunaticwhat** [comment]
not bug / issue related. You can ask for more information in our [Discord server](https://discord.gg/grasscutter)
