### ISSUE TITLE
[Feature Request] why we need Reflection

### ISSUE THREAD

**Issue by HelloTo4x** [Grasscutters/Grasscutter#1095]
Hi all, why do we need the Reflection in this, thank : https://github.com/Grasscutters/Grasscutter/blob/stable/src/main/java/emu/grasscutter/scripts/serializer/LuaSerializer.java

**Comment by zhaodice** [comment]
to interact with LUA, should use reflection for making a available JAVA Object reflected to LUA

**Comment by HelloTo4x** [comment]
you mean LUA programming ? why do u need it, what is the purpose of it

**Comment by zhaodice** [comment]
> you mean LUA programming ? why do u need it, what is the purpose of it

implement the trigger logic,example: 
quest, challenge, chest lock(should kill monsters to unlock), etc.

**Comment by HelloTo4x** [comment]
> > you mean LUA programming ? why do u need it, what is the purpose of it
> 
> implement the trigger logic,example: quest, challenge, chest lock(should kill monsters to unlock), etc.

hi, and about MITM proxy, why do u need it
