### ISSUE TITLE
[Bug] ./resources/QuestEncryptionKeys.json not found

### ISSUE THREAD

**Issue by simo8102** [Grasscutters/Grasscutter#1598]
Did you look for other closed issues that have the same problem?
Yes. But it didn't solve my problem

Describe the bug

All resources have been downloaded and mv Resource -> resource

console log:
<ERROR:ResourceLoader> Unable to load quest keys - ./resources/QuestEncryptionKeys.json not found.

Which branch did you use?

Grasscutter version: 1.2.3-dev
Git Hash: https://github.com/Grasscutters/Grasscutter/commit/78235f2f7e887689aaefd61da5797c95acb78bf2

Screenshots

Additional context

**Comment by Hartie95** [comment]
This already solves it, by linking the file needed:
https://github.com/Grasscutters/Grasscutter/issues/1588#issuecomment-1196817286

They are also only needed for 2.7+ prerendered cutscene support.
