### ISSUE TITLE
[Bug] Is there a patch for Genshin3.3?

### ISSUE THREAD

**Issue by mcoi-dev** [Grasscutters/Grasscutter#2001]
**Did you look for other closed issues that have the same problem?**

Some people asked about patch for 2.8, but it's 3.3 now.

**Describe the bug**

When I log in in my server, It says :"无法连接服务器，错误码4214"（`Error 4214`）And I tried `Cultivation` but it sais there's no patch for 3.3.

**Which branch did you use?**

Genshin Impact 3.3 (Not yuanshen) + GC 1.4.5 dev + fidder.

**Screenshots**

![](https://github.com/mcoi-dev/Pictures/raw/main/%E6%90%9C%E7%8B%97%E6%88%AA%E5%9B%BE20221227154209.png)

![](https://github.com/mcoi-dev/Pictures/raw/main/1.png)

![](https://github.com/mcoi-dev/Pictures/raw/main/3.png)

**Comment by mcoi-dev** [comment]
And is there a response for patch for Genshin impact?

**Comment by awaaer** [comment]
补丁工具
https://github.com/34736384/RSAPatch
打了就可以进去了

中国用户可用
https://www.123pan.com/s/gk5KVv-zD8A3
补丁下载链接
放在游戏Genshin Impact\Genshin Impact Game 目录下，记得备份原有文件
启动代理和游戏，看到CMD与游戏一起打开并运行即可

**Comment by mcoi-dev** [comment]
谢谢

**Comment by mcoi-dev** [comment]
终于找到了

**Comment by mcoi-dev** [comment]
为什么还是4214呢？替换了啊，也出现`cmd`窗口了

**Comment by mcoi-dev** [comment]
请问打开了还是4214怎么办？

**Comment by awaae001** [comment]
建议检查一下您的代理

**Comment by mcoi-dev** [comment]
代理fidder和mix都试过了，还试过大神手写的代理

**Comment by mcoi-dev** [comment]
host也没改

**Comment by awaae001** [comment]
6

**Comment by awaae001** [comment]
用一下GC启动器？

**Comment by mcoi-dev** [comment]
GC也试过了，账号直接没法登录，也试过GCX，能进去，但是登录进去就502

**Comment by mcoi-dev** [comment]
我严重怀疑我电脑是不是有问题，是不是应该重装系统

**Comment by awaae001** [comment]
系统自带的代理
![image](https://user-images.githubusercontent.com/108462724/209753422-382997db-557d-494b-ad0f-d5d78b07874d.png)

？

**Comment by mcoi-dev** [comment]
我试试

**Comment by mcoi-dev** [comment]
里面怎么填啊

**Comment by awaae001** [comment]
你要连接的服务器地址

**Comment by mcoi-dev** [comment]
难不成是我`dev-sidecar`的锅吗？

**Comment by mcoi-dev** [comment]
连接的是127.0.0.1:443啊

**Comment by awaae001** [comment]
你开了VPN？

**Comment by mcoi-dev** [comment]
我关了再试一次

**Comment by mcoi-dev** [comment]
还是不行。。。

**Comment by awaae001** [comment]
截屏

发过来

**Comment by awaae001** [comment]
？

**Comment by mcoi-dev** [comment]
额请问系统的代理开了还需要开fiddler吗？

**Comment by awaae001** [comment]
不用
系统代理是全局

开了就上不了网了

**Comment by awaae001** [comment]
实在不行试试这个
https://github.com/Grasscutters/GrassClipper/releases/

教程
https://blog.csdn.net/qq_42011565/article/details/125295810

**Comment by mcoi-dev** [comment]
GrassCliper试过了，也是不行

**Comment by awaae001** [comment]
+QQ
3271436144

**Comment by mcoi-dev** [comment]
您的QQ是以德服人那个吗？

**Comment by mcoi-dev** [comment]
我录屏吧

**Comment by awaae001** [comment]
是的
我的邮箱有延迟

**Comment by awaae001** [comment]
?接受了

**Comment by BNQDZJ** [comment]
如果出现4206是因为什么？

**Comment by KingRainbow44** [comment]
check out solutions listed above (namely RSAPatch)

**Comment by awaae001** [comment]
>邮箱
awaae001@qq.com
国际用户可用
awaae001@54pqj6.onmicrosoft.com
