### ISSUE TITLE
[Feature Request] Boss phasing

### ISSUE THREAD

**Issue by thecutefinder** [Grasscutters/Grasscutter#2109]
**Is your feature request related to a problem? Please describe.**
Support issues:
- 1095502272890425464
- Further down in 1056494423564890112, though the original post was unrelated to boss phasing.

**Describe the solution you'd like**
Boss phasing, meaning that bosses can go through each part of their battle, like Scaracoochie's two different forms, the part of the Ei battle that happens after Miko appears, etc.

**Comment by NotThorny** [comment]
This was implemented in the unstable-quest branch in https://github.com/Grasscutters/Grasscutter/commit/71a8ca2a8adb3b5502688f7b692e5d7c275e951b
