### ISSUE TITLE
Resources 页面失效

### ISSUE THREAD

**Issue by uchzmal** [Grasscutters/Grasscutter#2391]
![image](https://github.com/Grasscutters/Grasscutter/assets/117048798/ed49f773-f317-44fe-b19a-65f5b03c1485)
![image](https://github.com/Grasscutters/Grasscutter/assets/117048798/6cc577ef-1967-44a6-81cc-f51cd6b0e931)

**Comment by KingRainbow44** [comment]
see https://gitlab.com/YuukiPS/GC-Resources
